ALTER TABLE users ADD COLUMN assigned_db VARCHAR(100) DEFAULT 'shpsk';


ALTER TABLE terms 
ADD COLUMN updated_at TIMESTAMP NULL DEFAULT NULL;

ALTER TABLE terms 
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;



